# https://docs.crabnebula.dev/cloud/ci/tauri-v2-workflow/
on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Type of runner to use."
        required: false
        default: "github"
        type: choice
        options:
          - "warp"
          - "github"
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
env:
  TAURI_CONF_PATH: ./src-tauri/tauri.conf.json
jobs:
  build:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos"
            target: "aarch64-apple-darwin"
            runner: "macos-latest"
          - platform: "macos"
            target: "x86_64-apple-darwin"
            runner: "macos-latest"
          # - platform: "windows"
          #   target: "x86_64-pc-windows-msvc"
          #   runner: "${{ inputs.runner == 'warp' && 'warp-windows-latest-x64-4x' || 'windows-latest' }}"
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - run: |
          VERSION=$(jq -r '.version' ./apps/desktop/src-tauri/tauri.conf.json)

          if [[ "${{ github.event_name }}" == "release" ]]; then
            TAG_NAME="${{ github.event.release.tag_name }}"
            echo "Version: $VERSION, Tag name: $TAG_NAME"
            if [[ ! "$TAG_NAME" == *"$VERSION"* ]]; then
              exit 1
            fi
          fi
        shell: bash
      - uses: ./.github/actions/setup_protoc
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/install_desktop_deps
        with:
          target: ${{ matrix.platform }}
      - uses: ./.github/actions/rust_install
        with:
          platform: ${{ matrix.platform }}
      - uses: ./.github/actions/pnpm_install
      - uses: ./.github/actions/poetry_install
      - run: poetry run python scripts/pre_build.py
      - run: pnpm -F desktop lingui:compile
      - run: pnpm -F ui build
      - name: Build (dev/unsigned)
        run: pnpm -F desktop tauri build --target ${{ matrix.target }} --config ${{ env.TAURI_CONF_PATH }} --verbose --debug
        env:
          # https://github.com/tauri-apps/tauri-action/issues/740
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Collect build outputs
        shell: bash
        working-directory: ./apps/desktop/src-tauri
        run: |
          set -euo pipefail
          mkdir -p target/release/
          if [[ -d "target/${{ matrix.target }}/release" ]]; then
            find target/${{ matrix.target }}/release -type f -not -path "*/\.*" -exec cp {} target/release/ \;
          elif [[ -d "target/${{ matrix.target }}/debug" ]]; then
            find target/${{ matrix.target }}/debug -type f -not -path "*/\.*" -exec cp {} target/release/ \;
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: hyprnote-desktop-dmg-${{ matrix.target }}
          path: |
            apps/desktop/src-tauri/target/release/*.dmg
            apps/desktop/src-tauri/target/${{ matrix.target }}/release/bundle/dmg/*.dmg
            apps/desktop/src-tauri/target/${{ matrix.target }}/debug/bundle/dmg/*.dmg
            apps/desktop/src-tauri/target/${{ matrix.target }}/release/bundle/macos/*.app
            apps/desktop/src-tauri/target/${{ matrix.target }}/debug/bundle/macos/*.app
          if-no-files-found: warn
          retention-days: 14
